### PR TITLE
Rewrite to use Crypt::OpenSSL::Guess

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
Implementation of https://github.com/dsully/perl-crypt-openssl-x509/issues/97
Crypt::OpenSSL::Guess has support for all use cases implemented in this Makefile.PL

### CODE REVIEW

**Comment by skaji** [comment]
> LIBS => ['-lssl -lcrypto '.openssl_lib_paths()],

should be

> LIBS => [openssl_lib_paths() . ' -lssl -lcrypto'],

cf https://github.com/akiym/Crypt-OpenSSL-Guess/pull/12

**Comment by michal-josef-spacek** [comment]
@skaji Fixed

**Comment by michal-josef-spacek** [comment]
@skaji Same sitation with OpenSSL 3 was before.

**Comment by michal-josef-spacek** [comment]
@skaji Your #100 with `-DOPENSSL_API_COMPAT=0x10000000L` is working for me. I tested unit tests on OpenSSL 3.0.1 and 1.1.1l

**Comment by mmcclimon** [comment]
+1 to this PR. I couldn't install after messing around with my openssl libs, and applying this patch got me up and running.

**Comment by jonasbn** [comment]
Thanks for the feedback @mmcclimon. Easter holiday is coming up, I hope I can get it reviewed and merged and released

**Review by jonasbn — APPROVED** [review]
LGTM, approved

**Comment by jonasbn** [comment]
Thanks @michal-josef-spacek for the PR and thanks @skaji and @mmcclimon for review and test

**Comment by jonasbn** [comment]
I have marked this as solving #97 a TRIAL release, well let us know if this works out as expected, else we will just reopen #97

**Comment by jonasbn** [comment]
Hi @skaji, @michal-josef-spacek and @mmcclimon 

This has been included in the release [1.9.14-TRIAL](https://github.com/dsully/perl-crypt-openssl-x509/releases/tag/1.9.14-TRIAL), just uploaded to PAUSE/CPAN.

Please let me know if you experience any issues or have any feedback. The 1.9.14 release will be made in due time depending on the outcome/feedback of the trial release.

Thanks for your contributions.

**Comment by mmcclimon** [comment]
Works for me, thanks!

**Pull request merged**
